# Generated by Django 3.0.8 on 2021-01-14 17:34

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(max_length=255, unique=True)),
                ('registration_target', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive devices will not be sent notifications')),
                ('platform', models.CharField(blank=True, choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('CHROME', 'Web')], max_length=7, null=True)),
                ('connect_date', models.DateField(blank=True, null=True)),
                ('app_version', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
